### ISSUE TITLE
Get suncg object node ID from instance color

### ISSUE THREAD

**Issue by DakshIdnani** [facebookresearch/House3D#56]
Hi, I see that by using api.getNameFromInstanceColor we can get the model ID corresponding to the object at some pixel. However, the model ID does not map uniquely to object instances (for example there can be 2 distinct chairs in a frame with the same model ID). 

Is it possible to get the suncg node ID from an instance color?

**Comment by ppwwyyxx** [comment]
It is not possible now. The obj file includes names of objects in lines like:
```
g Object#1_104
g Model#s__497
# vertexes of the object ...
```
where the "object.." line contains the object id, and "model..." contains the model id.
However all the vertexes are defined in the section "model...", which means after loading the obj file, the object id information is lost.

One way to solve this is to process your obj file so that the section of each object contains both model id and object id, and parse this information in C++.

**Comment by DakshIdnani** [comment]
Alright, thank you for your input. I will probably extract the 3D bounding boxes of all the objects in the scene and use a perspective transformation using the camera properties to infer the object IDs for each frame.
